parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $cookieCategories: '%cookie_consent.categories%'
            $useLogger: '%cookie_consent.use_logger%'
            $cookieConsentPosition: '%cookie_consent.position%'
            $cookieConsentSimplified: '%cookie_consent.simplified%'
            $httpOnly: '%cookie_consent.http_only%'
            $formAction: '%cookie_consent.form_action%'
            $csrfProtection: '%cookie_consent.csrf_protection%'
            $privacyPolicyUrl: '%cookie_consent.privacy_policy_url%'

    Stulipan\CookieConsentBundle\:
        resource: '../../'
        exclude: '../../{vendor}'

    Stulipan\CookieConsentBundle\Controller\:
        resource: '../../Controller/*'
        public: true

    Stulipan\CookieConsentBundle\Cookie\CookieChecker:
        arguments: ["@=service('request_stack').getCurrentRequest()"]

    Stulipan\CookieConsentBundle\Cookie\CookieLogger:
        arguments:
            $request: "@=service('request_stack').getCurrentRequest()"
